### PR TITLE
fix build with g++ (Ubuntu 12.2.0-17ubuntu1) 12.2.0

### PR DESCRIPTION
**Pull request by odrevet**
I am using g++ (Ubuntu 12.2.0-17ubuntu1) 12.2.0, when make I have this error: 
src/AsmFile.cpp:160:38: error: ‘istream_iterator’ is not a member of ‘std’
this little MR simply add <iterator> header to AsmFile.h so it compiles under linux

### CODE REVIEW

**Comment by lordmir** [comment]
Nice catch 👍
